import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalStyle } from "@/styles";
import './reset.css'
import { Header } from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div
        className={GlobalStyle.background}
        >
        <img
          src="images/SVG/FOND.svg"
          className={GlobalStyle.background__image}
        />
        <div>
          <Header/>
          {children}
        </div>
      </div>
        </body>
  </html>
  );
}
